### ISSUE TITLE
severity map fiel validation debería rasterizar como no-data los pixeles sin punto, no como ceros

### ISSUE THREAD

**Issue by damateos** [qcooperative/qgis-epyris-plugin#2]
Cero es uno de los valores posibles del mapa de severidad.
así la validación debería comparar sólo los pixeles que tenían un punto de la capa de entrada.
Adjunto archivo ejemplo para validar: [puntos_campo.zip](https://github.com/qcooperative/qgis-epyris-plugin/files/4585810/puntos_campo.zip)

El algoritmo está devolviendo todos los resultados necesarios.

**Comment by luipir** [comment]
ok, ponerlo explicito tambien en la documentacion porfa

**Comment by luipir** [comment]
hecho el fix... rasterizaba generando una raster la mas sencilla para ahorrar espacio, o sea la hacia a Byte, pero esto limita los valores y nodata de default = -9999 no podia ser usado. Ademas no se inicializaba la raster a NODATA en fase de creacion.
